### ISSUE TITLE
Windows 10 build is still not active on the microsoft store.

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin-uwp#22]
I read on the subreddit that it needed to be resubmited, but it was 2 months old, wondering why it wont show up.

**Comment by spiriapbergeron** [comment]
On the windows store, it only appears to be available for XBOX, not PC.
 
I tried to unzip the .appxupload, to find the .appxbundle, and install from that, but Win10 won't let me install it because the certificate isn't valid, and the certificate is nowehere to be found.

**Comment by Darkwolf1515** [comment]
> On the windows store, it only appears to be available for XBOX, not PC.
> 
> I tried to unzip the .appxupload, to find the .appxbundle, and install from that, but Win10 won't let me install it because the certificate isn't valid, and the certificate is nowehere to be found.

I wish I had a link but I started this cause one of the main devs on the subreddit said the windows build was ready to go at the same time as the Xbox version, but was rejected by Microsoft while the Xbox version was approved. They said they would resubmit it but that was 2 months ago.

**Comment by MrTimscampi** [comment]
Paging @anthonylavado, since he's the one who handles stores for us.

**Comment by anthonylavado** [comment]
Yeah, sorry about that. I think we held off because of the issues with playback/connecting that the current version has. 
I would say our Web browser version and using any one of the other utilities (like MPV Shim) may be the better solution in the meanwhile. This current version just wraps the web browser inside a full screen view - it doesn't gain any better codec support or anything at the moment.

**Comment by spiriapbergeron** [comment]
Is there a way to have an installable version here on github, instead of just being SOL ?

**Comment by anthonylavado** [comment]
@spiriapbergeron It's worse than using the browser, but I'll see what we can do.

> SOL

This makes me not want to do it but ok

**Comment by spiriapbergeron** [comment]
Ah, I'm very sorry for being rude. I really didn't mean it that way, and my comment was done in poor judgement. I apologize.

I was frustrated for having spent like 5 hours trying to figure out why it wouldn't install, or show up in the MS store, or wondering why the 0.8.0 "downloadable" was in a form (.appxupload) meant to be uploaded to the store (???) and not installable locally (was I supposed to upload it to the store?).

After lots of fudging around, it's was a happy accident that I found I could unpacked it with 7-zip and found the .appxbundle, but that turned into more confusion when it wouldn't install, and eventually figured I needed a certificate, but not finding said certificate. It just left me really confused about where and how I could try this thing.

It's OK if it's not working right, but at least mention it in the readme, or provide a workaround?

For what it's worth, I myself only wanted to try having a full-screen client on a cheap Atom x64 Windows box (didn't want to buy an Android tv box just for this purpose) to run at startup in full-screen, as a dedicated JF client. I didn't want to have to launch a browser, connect to an IP, maximize the app, then press the fullscreen button... To me using a browser was just a poor experience, which is why I wanted to try the wrapper.

But in the end, I found I could use Chrome in Kiosk-fullscreen mode launched at the Windows startup. It's working OK as a workaround.

**Comment by spiriapbergeron** [comment]
Oh, and I was unaware of MPV shim... Thanks for pointing it out.

**Comment by anthonylavado** [comment]
A lot of the difficulty stems from the fact that a lot of it was set up by a contributor, so we're not even fully aware in how the whole process works. The certificate gets added by Microsoft when you send it for publishing, so we never added one ourselves. It's something I'll look in to though :-)

Also - if you've got it working in Fullscreen mode, try the TV Layout. (Click on your user profile at the top right, click Display, change layout from Auto to TV, reload webpage.)

**Comment by Darkwolf1515** [comment]
Thanks for responding, I don’t mind continuing to use shim right now. From what I read you’re saying uwp is just a wrapper anyways. Hopefully desktop is working soon as it builds for windows now but the dev flat out says it’s broken for all versions (which he is right about)

**Comment by spiriapbergeron** [comment]
Of course, now that I've got it running in the browser (the shim doesn't seem to give me anything extra) the problem is with the remote :) as I can't use the left-right buttons to go from one movie to another, and the up-down button act as a scrollbar rather than switching rows.  The home button spawns another chrome. Wee! Sorry, that was off-topic.

**Comment by Darkwolf1515** [comment]
> Of course, now that I've got it running in the browser (the shim doesn't seem to give me anything extra) the problem is with the remote :) as I can't use the left-right buttons to go from one movie to another, and the up-down button act as a scrollbar rather than switching rows. The home button spawns another chrome. Wee! Sorry, that was off-topic.

Not sure what you mean by “does nothing extra”, it creates a window on your desktop that can natively play a lot more files than the browsers ever could.

**Comment by anthonylavado** [comment]
Hi all, just as a heads up - the current builds of the UWP app don't actually work with 10.6. As a result, we've even pulled it from the Microsoft Store for Xbox for the time being. No timeline on an update, but using Edge (the browser) should work.

**Comment by Darkwolf1515** [comment]
> 
> 
> Hi all, just as a heads up - the current builds of the UWP app don't actually work with 10.6. As a result, we've even pulled it from the Microsoft Store for Xbox for the time being. No timeline on an update, but using Edge (the browser) should work.

Not a dev, but i'm interested in the process, if you have the time, can you answer how the update broke what I thought you said was a web wrapper, shouldn't it work exactly like it was in a browser?

**Comment by anthonylavado** [comment]
As a web wrapper, it loads the webpage from your server. The current issue is that there were changes to the web interface that are causing issues with the build of Edge that's used on the Xbox.

So it's not really the UWP app's fault. The Xbox uses the old EdgeHTML engine, and there's javascript issues with it when the new version is used.

We'll hopefully get to figure something out.

**Comment by anthonylavado** [comment]
As a update to cap this off, we did resolve the profile detection issue, so it *does* work now, but we still recommend Videotape because it has libVLC, for better playback support. So we'll still retire this for the time being.
