### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-uwp#36]
Just making a separate issue to have a more easily tracked conversation.

@Killerherts I apologize for not responding sooner - I am working on the publishing in between more Windows setup fixes. I have had to make new certificates and change some things in the Microsoft Partner Center. I had some details lost/mixed up as it's been a while since we published.

I've got the changes made in VS, so tonight I can re-package and try submitting again.

---

For anyone else following along, I'm working on publishing the Webview2 update, so hopefully things go a little smoother on the next time you use an Xbox to play back media.

**Comment by uzsbou** [comment]
Jellyfin updated itself today and it's kind of broken now. I can start a video but can't pause it or back out of it and subtitles (if you can call them that? Watching a show that they should just be there because it's a dual language show) aren't showing up. Is it because of this?

**Comment by Killerherts** [comment]
@uzsbou 

I am on the updated version, my subtitles work and the b button exits the video as well as arrow in top left corner.

Subtitles play automatically is a player preference I think smart is default I used always on and my mine appeared as I expected 

The only issue I have been able to recreate is the pause button issue and is solved by holding the button down. I'll have to try to dig into why the key down is being triggered multiple times while on the play button.

**Comment by dfederm** [comment]
Just updated and the app seems pretty broken. Video playback doesn't seem to work at all and the controls are certainly lacking.

**Comment by uzsbou** [comment]
@Killerherts

We are having very different experiences. I'll try reinstall tonight and report back if it fixes anything. Looks like I'm not the only one having issues @dfederm

**Comment by Killerherts** [comment]
@anthonylavado this does appear to be a issue the experience is not matching the one I was having in dev mode.

**Comment by anthonylavado** [comment]
I think I can do a rollback tonight. Unfortunately I'm out for the next 6-8 hours.

**Comment by anthonylavado** [comment]
I've submitted the older release as a new package, and sent it for certification. As soon as it passes, it will automatically release.

**Comment by uzsbou** [comment]
@anthonylavado this release is working normally for me now (in my limited lazy "I'm gonna watch this show" state). Thank you for your time!

**Comment by Killerherts** [comment]
I apologize for the issue thanks Anthony for the quick recovery. I'll come up with a new testing method for updates to the app. 

Anthony lmk if we are rebasing back to the roll back or what best course of action. I'll take steps to ensure this doesn't happen in the future.

**Comment by uzsbou** [comment]
I guess it's not working normally after all. Back to the way it was. I also ran into an issue trying to watch a preview. The preview started playing in the background with library on top of it. Had to force close the client to exit. Using edge browser in place of the client

**Comment by Killerherts** [comment]
It appears that you will need to uninstall and reinstall since this is a rollback for app to return to old version. 
I'll work on a better method of testing. Rebasing off our last release will be where I work from.

**Comment by dfederm** [comment]
Thanks for the quick rollback @anthonylavado 

And thanks @Killerherts for the follow-up. I know it can be frustrating to try and improve things and then it breaking :(. I for one really want 4k support so was hoping your change would help with that.

Do you have any ideas what went wrong? For me at least, when starting a video it appeared like it was being casted or something instead of being a "normal" video player. Even going to web UI in edge and playing a video showed a different player than the new app did, and presumably WebView2 should have behaved basically just like Edge AFAIK.

I've been kicking around the idea of trying to work on a native xbox app, but haven't really committed yet since it seems like a ton of work, and I'm personally not super familiar with XAML (actually one motivation is to use it as a learning opportunity). WebView2 might be a good incremental improvement for the immediate term, but do you have any desire to work on a more native experience?

**Comment by Killerherts** [comment]
@dfederm 
The issues with this update was my approach of abandoning the jellyfin.util in favor for build in webview2 stuff as the API calls have changed and webview2 is not a direct drop in replacement. 

Webview2 uses chromium underlying hence why the app is identified differently by the sever. 

The issue with this update stemmed from my decision to abandon jellyfin.util in favor of built-in WebView2 functionalities, as the API calls had changed, and WebView2 isn't a direct drop-in replacement. WebView2, utilizing Chromium underneath, causes the app to be identified differently by the server.

My plan is to rewrite jellyfinwebview.xaml entirely. Initially, I attempted to avoid this by simply inserting the URL into WebView2 and letting the XAML UI handle it. The oversight regarding the URL not saving was a simple mistake on my part, and I'll revert to using the current system in the future.

Regarding the native client, I was collaborating with someone, and we had reached the stage of loading and playing videos, but it was only a basic proof of concept. I halted work on it because I didn't have much interest in maintaining a native app. I prefer the app to stay aligned with the web player without needing manual updates. Using just a WebView still seems like the path of least resistance, so I ceased investing time in it.

I'm willing to assist, lead, or allow someone with more experience to take charge of these ideas. However, interest in UWP and the Xbox app for development work has been low.

Native or webview I'm am open to working on either.

**Comment by dfederm** [comment]
Dang, post rollback I'm now getting that it can't connect to the server. Works in Edge though.  So unfortunately it seems that something is still broken.

**Comment by anthonylavado** [comment]
I'll have to dig further, but I'll be 100% honest and say that we're pretty focused on 10.9 at the moment so it'll be tough to squeeze in more time for this. I think I'll try to build off the commit right before I merged the webview2 stuff down to main, and see if that does any better.

**Comment by Killerherts** [comment]
> I'll have to dig further, but I'll be 100% honest and say that we're pretty focused on 10.9 at the moment so it'll be tough to squeeze in more time for this. I think I'll try to build off the commit right before I merged the webview2 stuff down to main, and see if that does any better.

I am fixing the url validation and I can submit a PR I am just trying to make sure I don't create work twice for anyone. I should be able to have it ready soon I am just making sure exceptions for the url are handled better and I have time to test it.

**Comment by Killerherts** [comment]
PR #40 addresses these issues. It has been rebased on the October 2, 2022 update and resolves some edge cases with URL validation. This update ensures proper handling of redirects.

@dfederm, if you have an Xbox dev kit set up, feel free to pull from my Recover branch and test your URLs. I tested with my FQDN local address and the demo.jellyfin.org site all worked. I also tested theses with incorrect protocol, and it was corrected for the user.

In the long run, I still aim to explore WebView2 for improved player support, particularly regarding codecs and bit rates.

@anthonylavado Thanks for your help, I won’t submit anything until we are past 10.9.

Thanks for your patience, everyone.

**Comment by JamieMcH** [comment]
As 10.9 has been out for a bit, is there any update on this?

**Comment by greatestradioshow** [comment]
I'm also wondering if there is any update? 
My setup:
> Server: 10.9.6
> Xbox Series X: 10.0.25398.4478
> Jellyfin Xbox App: 0.8.0.70

I'm not able to log in to my server on my Xbox. On all other platforms (Windows, Android, iOS, Tizen) it works.

**Comment by Killerherts** [comment]
@anthonylavado can we get this pushed to the Ms store sorry to be a bother

**Comment by anthonylavado** [comment]
Alright, the "fixed" build as currently in the repo is in certification. Should just be a day or two before Microsoft clears it. Then we can move forward. I'll post another update here when that happens, and then close the issue to make a new one for future work.

**Comment by anthonylavado** [comment]
Looks like it went live as of 8:53 AM EDT (12:53 UTC), and in my basic tests, everything seems to be working.

We'll close this out and make a new item for upcoming improvements.

**Comment by danielson317** [comment]
Latest works perfectly on my xbox one s. Thanks for your hard work.

**Comment by dfederm** [comment]
@Mr20yearsintech See #48
